"""Axiomize report archive indexer.

Scans reports/*.md produced by modeling sessions, extracts the header fields
the report template guarantees (Date, Rigor level, Model in one sentence),
and regenerates reports/INDEX.md so sessions accumulate into a searchable
archive.

Usage (run in the directory that contains a reports/ folder):
    python index_reports.py            # rebuild INDEX.md
"""

import datetime
import re
import sys
from pathlib import Path

FIELDS = ["Rigor level", "Model in one sentence"]


def parse_report(path):
    text = path.read_text(encoding="utf-8", errors="replace")
    title_m = re.search(r"^# Model Report:\s*(.+)$", text, re.M)
    date_m = re.search(r"\*\*Date:\*\*\s*([0-9]{4}-[0-9]{2}-[0-9]{2})", text)
    rigor_m = re.search(r"\*\*Rigor level:\*\*\s*(\w+)", text)
    model_m = re.search(r"\*\*Model in one sentence:\*\*\s*(.+)", text)
    return {
        "file": path.name,
        "title": title_m.group(1).strip() if title_m else path.stem,
        "date": date_m.group(1) if date_m else "",
        "rigor": rigor_m.group(1) if rigor_m else "",
        "model": model_m.group(1).strip() if model_m else "",
    }


def main():
    reports_dir = Path.cwd() / "reports"
    if not reports_dir.is_dir():
        print("no reports/ directory here - nothing to index")
        return 0

    entries = [parse_report(p) for p in sorted(reports_dir.glob("*.md")) if p.name != "INDEX.md"]
    entries.sort(key=lambda e: e["date"], reverse=True)

    lines = [
        "# Modeling Session Index",
        "",
        f"_Auto-generated by skills/axiomize/tools/index_reports.py on "
        f"{datetime.date.today().isoformat()} - do not edit by hand._",
        "",
        f"{len(entries)} session(s):",
        "",
        "| Date | Report | Rigor | Model in one sentence |",
        "|------|--------|-------|------------------------|",
    ]
    for e in entries:
        model = e["model"].replace("|", "/")
        lines.append(f"| {e['date']} | [{e['title']}]({e['file']}) | {e['rigor']} | {model} |")
    lines.append("")

    out = reports_dir / "INDEX.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"indexed {len(entries)} report(s) -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
