"""Additional portable/model-document exports for Model IR.

These are explicit adapters, not claims of external-standard compliance. SBML,
CellML and notebook exports remain in :mod:`axiomize.standards_export`.
"""
from __future__ import annotations

import ast
import html
import re
from typing import Any

import sympy as sp

from axiomize.model_ir import ModelFamily, ModelIR
from axiomize.safe_expression import sympy_expression


def _symbols(model: ModelIR) -> dict[str, Any]:
    names = [model.independent_variable, *[v.name for v in model.variables], *[p.name for p in model.parameters]]
    return {name: sp.Symbol(name, real=True) for name in names}


def _latex(model: ModelIR) -> dict[str, Any]:
    symbols = _symbols(model); rows = []
    for equation in model.equations:
        rhs = sp.latex(sympy_expression(equation.expression, symbols))
        if equation.kind == "derivative": lhs = rf"\frac{{d {equation.target}}}{{d {model.independent_variable}}}"
        elif equation.kind == "residual": lhs = "0"
        elif equation.target: lhs = sp.latex(symbols.get(equation.target, sp.Symbol(equation.target)))
        else: lhs = r"\mathcal{J}"
        rows.append(rf"{lhs} &= {rhs}")
    parameter_rows = [rf"{sp.latex(symbols[p.name])} & {'' if p.value is None else p.value} & \mathrm{{{p.unit}}}" for p in model.parameters]
    content = "\n".join([
        "% Generated by Axiomize from versioned Model IR", rf"\section*{{{model.name}}}",
        rf"\textbf{{Family:}} {model.family.value}\\", rf"\textbf{{Domain:}} {model.domain}\\",
        r"\begin{align}", " \\\n".join(rows), r"\end{align}",
        *( [r"\begin{tabular}{lll}", r"Parameter & Value & Unit \\ \hline", *[row + r" \\" for row in parameter_rows], r"\end{tabular}"] if parameter_rows else []),
    ])
    return {"status": "PASS", "format": "latex", "content": content, "detail": "LaTeX model report fragment; no shell execution is performed"}


def _mathml(model: ModelIR) -> dict[str, Any]:
    symbols = _symbols(model); equations = []
    for equation in model.equations:
        expr = sympy_expression(equation.expression, symbols)
        equations.append({"target": equation.target, "kind": equation.kind, "mathml": sp.printing.mathml(expr, printer="content")})
    body = "\n".join(f'<axiomize-equation target="{html.escape(row["target"])}" kind="{html.escape(row["kind"])}"><math xmlns="http://www.w3.org/1998/Math/MathML">{row["mathml"]}</math></axiomize-equation>' for row in equations)
    return {"status": "PASS", "format": "mathml", "content": f'<axiomize-model schema-version="{html.escape(model.schema_version)}">\n{body}\n</axiomize-model>', "equations": equations,
            "detail": "Content MathML expressions wrapped in Axiomize model metadata; this is not SBML/CellML"}


def _expression_names(expression: str) -> set[str]:
    tree = ast.parse(expression, mode="eval")
    return {node.id for node in ast.walk(tree) if isinstance(node, ast.Name)}


def _dot(model: ModelIR) -> dict[str, Any]:
    lines = ["digraph axiomize_model {", '  rankdir="LR";']
    if model.family == ModelFamily.CAUSAL:
        cfg = model.metadata.get("causal", {}) if isinstance(model.metadata, dict) else {}
        identification = cfg.get("identification", model.metadata.get("causal_identification", {})) if isinstance(cfg, dict) else {}
        raw = identification.get("dag", identification.get("edges", cfg.get("dag", []))) if isinstance(identification, dict) else []
        for edge in raw if isinstance(raw, list) else []:
            if isinstance(edge, dict): a, b = edge.get("source"), edge.get("target")
            elif isinstance(edge, (list, tuple)) and len(edge) == 2: a, b = edge
            else: continue
            lines.append(f'  "{str(a).replace(chr(34), chr(39))}" -> "{str(b).replace(chr(34), chr(39))}";')
    elif model.family == ModelFamily.NETWORK:
        cfg = model.metadata.get("network", {}) if isinstance(model.metadata, dict) else {}
        directed = bool(cfg.get("directed", False)) if isinstance(cfg, dict) else False
        op = "->" if directed else "--"
        if not directed: lines[0] = "graph axiomize_model {"
        for edge in cfg.get("edges", []) if isinstance(cfg, dict) else []:
            if isinstance(edge, dict): a, b = edge.get("source"), edge.get("target")
            elif isinstance(edge, (list, tuple)) and len(edge) >= 2: a, b = edge[:2]
            else: continue
            lines.append(f'  "{str(a).replace(chr(34), chr(39))}" {op} "{str(b).replace(chr(34), chr(39))}";')
    else:
        variable_names = {v.name for v in model.variables}; parameter_names = {p.name for p in model.parameters}
        for equation in model.equations:
            target = equation.target or f"{equation.kind}_{len(lines)}"
            lines.append(f'  "{target}" [shape=box];')
            for source in sorted(_expression_names(equation.expression) & (variable_names | parameter_names)):
                if source != target: lines.append(f'  "{source}" -> "{target}";')
    lines.append("}")
    return {"status": "PASS", "format": "dot", "content": "\n".join(lines), "detail": "Graphviz DOT dependency/causal/network graph"}


def _julia_expression(text: str) -> str:
    # Model IR grammar is deliberately close to Julia arithmetic. Convert only
    # exponentiation; unsupported Piecewise/Heaviside require an adapter.
    if re.search(r"\b(Piecewise|Heaviside)\s*\(", text): raise ValueError("Julia ODE export does not yet translate Piecewise/Heaviside")
    return text.replace("**", "^")


def _julia(model: ModelIR) -> dict[str, Any]:
    if model.family != ModelFamily.ODE:
        return {"status": "ADAPTER_REQUIRED", "format": "julia", "detail": "native Julia script export currently supports ODE Model IR", "portable_ir": model.to_dict()}
    states = [v for v in model.variables if v.role == "state"]
    by_target = {e.target: e for e in model.equations if e.kind == "derivative"}
    if any(v.name not in by_target for v in states): return {"status": "ADAPTER_REQUIRED", "format": "julia", "detail": "ODE state derivative equations are incomplete"}
    pnames = [p.name for p in model.parameters]
    lines = ["# Generated by Axiomize from Model IR", "using DifferentialEquations", "", "function f!(du, u, p, t)"]
    for i, state in enumerate(states, 1): lines.append(f"    {state.name} = u[{i}]")
    for i, name in enumerate(pnames, 1): lines.append(f"    {name} = p[{i}]")
    for i, state in enumerate(states, 1): lines.append(f"    du[{i}] = {_julia_expression(by_target[state.name].expression)}")
    lines += ["end", ""]
    initials = ["0.0" if v.initial is None else repr(float(v.initial)) for v in states]
    params = ["0.0" if p.value is None else repr(float(p.value)) for p in model.parameters]
    lines += [f"u0 = [{', '.join(initials)}]", f"p = [{', '.join(params)}]", "tspan = (0.0, 1.0)", "prob = ODEProblem(f!, u0, tspan, p)", "sol = solve(prob, Tsit5())", "println(sol)"]
    return {"status": "PASS", "format": "julia", "content": "\n".join(lines), "runtime": "Julia + DifferentialEquations.jl", "detail": "runnable ODE script; solver package installation is external"}


def _markdown(model: ModelIR) -> dict[str, Any]:
    lines = [f"# {model.name}", "", f"- Schema: `{model.schema_version}`", f"- Family: `{model.family.value}`", f"- Domain: `{model.domain}`", "", "## Variables", "", "| Name | Role | Unit | Initial |", "|---|---|---|---:|"]
    for v in model.variables: lines.append(f"| {v.name} | {v.role} | {v.unit} | {'' if v.initial is None else v.initial} |")
    lines += ["", "## Parameters", "", "| Name | Unit | Value | Fit |", "|---|---|---:|---|"]
    for p in model.parameters: lines.append(f"| {p.name} | {p.unit} | {'' if p.value is None else p.value} | {p.fit} |")
    lines += ["", "## Equations", ""]
    for e in model.equations: lines.append(f"- `{e.kind}` `{e.target}`: `{e.expression}`")
    if model.assumptions: lines += ["", "## Assumptions", *[f"- {a}" for a in model.assumptions]]
    return {"status": "PASS", "format": "markdown", "content": "\n".join(lines)}


def export_extended(model: ModelIR, *, format: str) -> dict[str, Any] | None:
    fmt = str(format).strip().lower().replace("_", "-")
    if fmt in {"latex", "tex"}: return _latex(model)
    if fmt in {"mathml", "mml"}: return _mathml(model)
    if fmt in {"dot", "graphviz"}: return _dot(model)
    if fmt in {"julia", "jl"}: return _julia(model)
    if fmt in {"markdown", "md", "model-card"}: return _markdown(model)
    return None
